export enum IAction {
  NEW = "new",
  COPY = "copy",
  EDIT = "edit",
  ARCHIVE = "archive",
  RESTORE = "restore",
  DELETE = "delete",
  // SAVE_MENU = "saveMenu",
  SAVE = "save",
  // SAVE_EDIT = "saveedit",
  // SAVE_NEW = "savenew",
  // SAVE_COPY = "savecopy",
  // SAVE_SUBMIT = "savesubmit",
  // SAVE_SEND = "savesend",
  // SAVE_APPROVE = "saveapprove",
  // SAVE_ACCEPT = "saveaccept",
  CANCEL = "cancel",
  CANCELVIEW = "cancelview",
  LIST = "list",
  VIEW = "view",
  ADD = "add",
  REGENERATE = "regenerate",
  ASSIGNMENT = "assignment",
  VIEWASSIGNMENT = "viewassignment",
  // ADD_EXT1 = "add_ext1",
  // SUBMIT = "submit",
  // SEND = "send",
  // RETURN = "return",
  // REJECT = "reject",
  // APPROVE = "approve",
  // APPROVE_NEW = "approvenew",
  // APPROVE_COPY = "approvecopy",
  // ACCEPT = "accept",
  // ACCEPT_NEW = "acceptnew",
  // ACCEPT_COPY = "acceptcopy",
  // MARKASBILLED = "markasbilled",
  // UNMARKASBILLED = "unmarkasbilled",
  // MARKASINVOICED = "markasinvoiced",
  // UNMARKASINVOICED = "unmarkasinvoiced",
  // ITEMINFO = "iteminfo",
  REFRESH = "refresh",
  // INVITE = "invite",
  PRINT = "print",
  // EMAIL = "email",
  CLEAR_SEARCH = "clearsearch",
  // PAYMENT = "payment",
  // NONE = "none",
  // ATTACHMENT = "attachment",
  MORE = "more",
  // ALLOCATE = "allocate",
  // UNALLOCATE = "unallocate",
  // UPLOAD = "upload",
  // DOWNLOAD = "download",
  // DECLINE = "decline",
  // LINK = "link",
  // STORAGE = "storage",
  // BROWSE = "browse",
  // ADJUST = "adjust",
  // ITEMADJUSMENT = "itemadjustment",
  // BOARD = "board",
  // ADD_PLANNEDDATE = "add_planneddate",
  IMPORT = "import",
  EXPORT = "export",
  // RUN = "run",
  // SETTING = "setting",
  // DISPOSE = "dispose",
  // ADD_TOGROUP = "add_togroup",
  // REMOVE_FROMGROUP = "remove_fromgroup",
  // MOVE_TOGROUP = "move_togroup",
  // ADD_GROUP = "add_group",
  // UPDATE_GROUP = "update_group",
  // DELETE_GROUP = "delete_group",
  // MERGE_CONTACT = "merge_contact",
  // REMINDER = "reminder",
  // PREVIEW = "preview",
  // CHANGE_DATE = "change_date",
  // NEW_FIXEDASSET = "new_fixed_asset"
}
export interface ITbarButton {
  key: IAction;
  type?: "submit" | "reset" | "button" | undefined;
  label?: string;
  icon?: string;
  items?: { key: IAction | "splitRegion"; sub?: string; label?: string, icon?: string; }[];
  isEditting?: boolean;
}
export interface IActionAndSub {
  key: IAction;
  sub: string;
}

export const actionButtons = [
  { icon: "new", key: "new", },
  { icon: "copy", key: "copy", },
  // { icon: "copyto", key: "copyto", },
  { icon: "edit", key: "edit", },
  { icon: "delete", key: "delete", },
  // { icon: "unallocate", key: "unallocate", },
  { icon: "save", key: "save", },
  { icon: "cancel", key: "cancel", },
  { icon: "list", key: "list", },
  // { icon: "approve", key: "approve", },
  // { icon: "accept", key: "accept", },
  // { icon: "decline", key: "decline", },
  // { icon: "return", key: "return", label: "Return", },
  // { icon: "reject", key: "reject", label: "Reject", },
  // { icon: "markasbilled", key: "markasbilled", },
  // { icon: "unmarkasbilled", key: "unmarkasbilled", },
  // { icon: "markasinvoiced", key: "markasinvoiced", },
  // { icon: "unmarkasinvoiced", key: "unmarkasinvoiced", },
  { icon: "add", key: "add", },
  // { icon: "invite", key: "invite", },
  { icon: "clearsearch", key: "clearsearch", },
  // { icon: "payment", key: "payment", },
  // { icon: "print", key: "print", },
  // { icon: "attachment", key: "attachment", },
  { icon: "more", key: "more", },
  // { icon: "upload", key: "upload", },
  // { icon: "download", key: "download", },
  // { icon: "link", key: "link", },
  // { icon: "storage", key: "storage", },
  // { icon: "browse", key: "browse", },
  // { icon: "adjust", key: "adjust", },
  // { icon: "allocate", key: "allocate", },
  { icon: "restore", key: "restore", },
  // { icon: "restore", key: "remove", },
  // { icon: "add_planneddate", key: "add_planneddate", },
  { icon: "import", key: "import", },
  { icon: "export", key: "export", },
  // { icon: "run", key: "run", },
  // { icon: "setting", key: "setting", },
  { icon: "dispose", key: "dispose", },
  { icon: "merge_contact", key: "merge_contact", },
  // { icon: "reminder", key: "reminder", },
  // { icon: "preview", key: "preview" },
];

export enum IModeForm {
  VIEW = "view",
  LIST = "list",
  FORM = "form",
  // BOARD = "board",
  // IMPORT = "import",
}
